### ISSUE TITLE
[PE-D] Mismatch of DG and ResultDisplay description regarding the `within` command

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T17-3/tp#150]
![image.png](https://raw.githubusercontent.com/9teMare/ped/main/files/b2816f1e-76c1-4338-b4a6-02bb875d919b.png)

![image.png](https://raw.githubusercontent.com/9teMare/ped/main/files/ce7a1cff-9e68-4ded-b37e-1e2b9ce6021e.png)

`Days` can actually be `0`, make sure to update UG accordingly.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: 9teMare/ped#4

**Comment by pyk595** [comment]
Duplicate issue, see #138
