### ISSUE TITLE
[PE-D] Problem with tag search documentation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T17-3/tp#154]
Command summary does not state that `TAG` is required after `#` which would confuse readers
![image.png](https://raw.githubusercontent.com/howardwhw2/ped/main/files/e1ddae18-0fd1-43a3-b4c4-a7b90061f58a.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: howardwhw2/ped#6

**Comment by ngjunkang** [comment]
Duplicate in #137.

**Comment by ngjunkang** [comment]
Duplicate of #137.
