### ISSUE TITLE
Improve Tagging feature

### ISSUE THREAD

**Issue by ngjunkang** [AY2122S2-CS2103T-T17-3/tp#37]
As a user with many persons in the address book, I want to assign tags to my contacts easily so that I can categorise my contacts in a meaningful manner.

This improvement should be closed upon the closure of #33, #34, #35 and #36.

**Comment by pyk595** [comment]
Closed as #33 , #34 , #35, #36  are completed and reviewed.

**Comment by ngjunkang** [comment]
I am pushing one general code quality commit later, just cleaning up some code, so I will close using the PR.

**Comment by pyk595** [comment]
Okay
